name: Test

on:
  push:
  pull_request:

jobs:
  test:
    name: Test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Moon env (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc libssl-dev
          curl -fsSL https://cli.moonbitlang.com/install/unix.sh | bash
          echo "$HOME/.moon/bin" >> "$GITHUB_PATH"

      - name: Setup Moon env (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install gcc openssl
          curl -fsSL https://cli.moonbitlang.com/install/unix.sh | bash
          echo "$HOME/.moon/bin" >> "$GITHUB_PATH"

      - name: Setup Moon env (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          Set-ExecutionPolicy RemoteSigned -Scope CurrentUser
          irm https://cli.moonbitlang.com/install/powershell.ps1 | iex
          echo "$HOME/.moon/bin" | Out-File -FilePath $env:GITHUB_PATH -Append

      - name: Setup MSYS2 + MinGW + openssl (Windows)
        if: runner.os == 'Windows'
        uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: >-
            mingw-w64-ucrt-x86_64-gcc
            mingw-w64-ucrt-x86_64-openssl

      - name: Moon Check
        run: |
          moon fmt --check
          moon check --deny-warn
          moon info
          git diff --exit-code
          git status

      - name: Moon test
        run: |
          echo moon test
          moon test --deny-warn --enable-coverage
          moon coverage report -f summary

          moon coverage analyze

          # ffi test
          echo moon test native
          moon test --deny-warn --target native --enable-coverage
          moon coverage report -f summary

          moon coverage analyze
